### PR TITLE
Added a method that will remove duplicate chars

### PR DESCRIPTION
**Pull request by Mari316**
Waiting for approval from at least 2 collaborators

### CODE REVIEW

**Comment by ZhannaSar** [comment]
Goof job

**Comment by Mari316** [comment]
> Goof job

Thank you, Zhanna! hopefully  **one more person**  from our collaborators will approve my code

**Review by maximvoronov757 — APPROVED** [review]
amazing

**Comment by maximvoronov757** [comment]
> > Goof job
> 
> Thank you, Zhanna! hopefully **one more person** from our collaborators will approve my code

Zhanna left comment without approval. I gave mine, but you still need one more

**Pull request merged**
