### PR TITLE
I created a custom method, which helps me to find first duplicate in a…

### PR DESCRIPTION
**Pull request by ZhannaSar**
Please review my codes

### CODE REVIEW

**Review by maximvoronov757 — APPROVED** [review]
This code looks soooooo good :)

**Comment by maximvoronov757** [comment]
If our coworker Marina is ok with this code than you can merge this PR

**Comment by maximvoronov757** [comment]
I already gave my approved

**Review by Mari316 — APPROVED** [review]
This code works fine. Lets merge it, Max could you please merge it to master?

**Pull request merged**
